# exception of muscle and hmmbuild which are one directory above the current working directory
 
#concatinate the gene sequence files together adding an \n to the end of each
for file in sporecoat*.fasta
        do
        echo \n >> $file
        cat $file >> sporecoatall.fasta
        done

for file in transporter*.fasta
        do
        echo \n >> $file
        cat $file >> tansporterall.fasta
        done

#muscle both files
 ../muscle3.8.31_i86linux32 -in sporecoatall.fasta -out sporecoat.aligned
 ../muscle3.8.31_i86linux32 -in transporterall.fasta -out transporter.aligned

#hmm build both files
../hmmbuild sporecoat.hmm sporecoat.aligned
../hmmbuild transporter.hmm transporter.aligned
